name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.0.0.rc2
        env:
          GITHUB_TOKEN: $ { { secrets.GITHUB_TOKEN }}